version: '3.9'

services:

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ../ecommerce-backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../ecommerce-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: ../ecommerce-backend
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    volumes:
      - ../ecommerce-backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  frontend:
    build: ../ecommerce-frontend
    restart: unless-stopped
    volumes:
      - ../ecommerce-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: